Feature: Create my custom worktop from scratch
  As a customer
  I want to create my custom worktop
  In order to get a price estimate

  Scenario Outline: F008 Create my custom worktop
    Given I have navigated to the plan page
    And I have selected shape <shape> with measurement <measurement> and wall selection <wall selection> in the plan tab
    And I have selected worktop material <worktop material>, expression <expression>, edge <edge> and thickness <thickness> in the style tab
    And I have selected splashback <splashback> with material <wall panel material> and expression <wall panel expression> in the style tab
    And I have selected sink material <sink material>, model <sink model>, fastening <sink fastening>, drainer grooves <drainer grooves> and <tap holes> tap holes in the sink tab
    And I have selected <hob cut outs> hob cut outs, <rounded corners> rounded corners, <inverted corners> inverted corners, <single cuts> single cuts, <double cuts> double cuts and <triple cuts> triple cuts in the cut outs page
    And I have selected <round cuts small> small round cuts, <round cuts big> big round cuts, <square cuts> square cuts, <wp single cuts> single cuts, <wp double cuts> double cuts and <wp triple cuts> triple cuts in the cut outs page
    When I navigate to the item-list page
    Then the it should include <worktop articles>, <sink articles>, <drainer groove articles>, <tap hole articles>, <hob cut out articles>, <single cut articles>, <double cut articles>, <triple cut articles>, <rounded corner articles>, <inverted corner articles>, <wall panel articles>, <round small cut articles>, <round big cut articles>, <square cut articles>, <wp single cut articles>, <wp double cut articles> and <wp triple cut articles>
    And the total price, both in the header and in the item list should be correct
      Examples:
      | shape       | measurement                | wall selection     | worktop material | expression                  | edge       | thickness | splashback        | wall panel material | wall panel expression       | sink material | sink model                                                  | sink fastening | drainer grooves | tap holes | hob cut outs | rounded corners | inverted corners | single cuts | double cuts | triple cuts | round cuts small | round cuts big | square cuts | wp single cuts | wp double cuts | wp triple cuts | worktop articles                                                                                                                                        | sink articles                                                                                             | drainer groove articles              | tap hole articles                | hob cut out articles            | single cut articles                | double cut articles            | triple cut articles              | rounded corner articles              | inverted corner articles             | wall panel articles            |  round small cut articles        | round big cut articles           | square cut articles              | wp single cut articles               | wp double cut articles            | wp triple cut articles               |
      | rectangular | 3500,600                   | two walls right    | solid wood       | oak                         | same color | 38        | none              | none                | none                        | steel         | HILLESJÖN inset sink 1 1/2 bowl stainless steel 58x46 cm    | topMounted     | no              | 1         | 1            | 0               | 0                | 1           | 0           | 0           | 0                | 0              | 0           | 0              | 0              | 0              | 3.5*(20345567 SKOGARP 45.1-63.5*4.0) + 0.6*(00350183 Same Color Edge Solid Wood)                                                                        | 1*(49140631 HILLESJÖN inset sink 1 1/2 bowl stainless steel 58x46 cm) + 1*(70345579 Cut Out Solid Wood)   | NA                                   | 1*(30345576 Tap Hole Solid Wood) | 1*(70345579 Cut Out Solid Wood) | 1*(70345579 Single Cut Solid Wood) | NA                             | NA                               | NA                                   | NA                                   | NA                             | NA                               | NA                               | NA                               | NA                                   | NA                                | NA                                   |
      | l-shape     | 3100,4320,400,430          | one wall left      | laminate         | black laminate              | aluminium  | 77        | wall panel        | laminate            | black laminate              | no sink       | NA                                                          | NA             | NA              | 0         | 1            | 2               | 0                | 0           | 0           | 1           | 0                | 0              | 0           | 0              | 0              | 0              | 6.99*(70345560 DEJE 10-45*7.7) + 2*(10345577 Joint Laminate) + 10.52*(40345571 Aluminium Edge 77 Laminate)                                              | NA                                                                                                        | NA                                   | NA                               | 1*(10345577 Cut Out Laminate)   | NA                                 | NA                             | 1*(10345577 Triple Cut Laminate) | 2*(10345577 Rounded Corner Laminate) | NA                                   | 2.38*(50216663 SIBBARP 1 m2)   | NA                               | NA                               | NA                               | NA                                   | NA                                | NA                                   |
      | u-shape     | 3510,2100,2990,635,635,800 | two walls left     | quartz           | white marble effect/quartz  | same color | 38        | wall edging strip | none                | none                        | composite     | HÄLLVIKEN 100x50 black                                      | topMounted     | no              | 1         | 1            | 0               | 0                | 0           | 2           | 0           | 0                | 0              | 0           | 0              | 0              | 0              | 2.99*(40345528 OXSTEN 63.6-125*3.8) + 4.18*(90345521 OXSTEN 45.1-63.5*3.8) + 4.43*(30350313 Same Color Edge Quartz) + 2*(50345580 Joint Quartz)         | 1*(79158196 HÄLLVIKEN 100x50 black) + 1*(50345580 Cut Out Quartz)                                         | NA                                   | 1*(80345574 Tap Hole Quartz)     | 1*(50345580 Cut Out Quartz)     | NA                                 | 2*(50345580 Double Cut Quartz) | NA                               | NA                                   | NA                                   | 5.61*(00345950 OTTARP)         | NA                               | NA                               | NA                               | NA                                   | NA                                | NA                                   |
      | v-shape     | 2500,2500                  | two walls          | acrylic          | white acrylic               | same color | 38        | wall panel        | acrylic             | white acrylic               | steel         | LÅNGUDDEN inset sink 2 bowls stainless steel 75x53 cm       | underGlued     | yes             | 0         | 0            | 0               | 2                | 0           | 0           | 0           | 0                | 0              | 1           | 0              | 1              | 0              | 1.51*(70345433 FORNBY 63.6-125*3.8) + 2.88*(50345434 FORNBY 45.1-63.5*3.8) + 1.27*(50350312 Same Color Edge Acrylic) + 4*(90345578 Preparation Acrylic) | 1*(70352032 LÅNGUDDEN inset sink 2 bowls stainless steel 75x53 cm)                                        | 1*(40345585 Drainer Grooves Acrylic) | NA                               | NA                              | NA                                 | NA                             | NA                               | NA                                   | 2*(90345578 Inverted Corner Acrylic) | 2.75*(40216649 KLINGSTA 1 m2)  | NA                               | NA                               | 1*(50346264 WP Cut out Acrylic)  | NA                                   | 1*(30345944 WP Cut out Acrylic)   | NA                                   |
      | c-shape     | 2000,3150                  | four walls right   | laminate         | dark oak effect laminate    | same color | 28        | wall panel        | laminate            | dark oak effect laminate    | steel         | VATTUDALEN 109x53                                           | topMounted     | no              | 1         | 0            | 0               | 0                | 0           | 0           | 0           | 0                | 0              | 0           | 0              | 0              | 0              | 6.14*(60345457 EKBACKEN 45.1-63.5*2.8) + 4*(10345577 Single Cut Laminate) + 0.64*(20350182 Same Color Edge Laminate)                                    | 1*(09158190 VATTUDALEN 109x53) + 1*(10345577 Joint Laminate)                                              | NA                                   | 1*(00345573 Tap Hole Laminate)   | NA                              | NA                                 | NA                             | NA                               | NA                                   | NA                                   | 3.79*(20311973 SIBBARP 1 m2)   | NA                               | NA                               | NA                               | NA                                   | NA                                | NA                                   |
      | ii-shape    | 900,450,5000,1100          | six walls          | laminate         | black stone effect/laminate | aluminium  | 28        | wall panel        | quartz              | whitequartz                 | steel         | BOHOLMEN inset sink 1 bowl stainless steel 47x30 cm         | underGlued     | no              | 2         | 1            | 1               | 0                | 2           | 0           | 0           | 0                | 1              | 2           | 1              | 0              | 0              | 0.9*(40345444 EKBACKEN 10-45*2.8) + 5*(20345478 EKBACKEN 63.6-125*2.8) + 1*(10345577 Joint Laminate) + 5.9*(60340558 Aluminium Edge 28 Laminate)        | 1*(60348031 BOHOLMEN inset sink 1 bowl stainless steel 47x30 cm)                                          | NA                                   | 2*(00345573 Tap Hole Laminate)   | 1*(10345577 Cut Out Laminate)   | 2*(10345577 Single Cut Laminate)   | NA                             | NA                               | 1*(10345577 Rounded Corner Laminate) | NA                                   | 4.93*(50311995 RÅHULT 1 m2)    | NA                               | 1*(30346260 WP Cut out Quartz)   | 2*(30346260 WP Cut out Quartz)   | 1*(60345947 WP Preparation Quartz)   | NA                                | NA                                   |
      | irregular   | 8000,200,635               | two walls top left | wood             | BARKABODA walnut            | same color | 38        | wall panel        | glass               | black glass                 | composite     | HÄLLVIKEN inset sink 1 bowl white quartz composite 56x50 cm | underGlued     | no              | 0         | 2            | 0               | 0                | 0           | 0           | 0           | 0                | 0              | 0           | 0              | 0              | 0              | 4*(10347557 BARKABODA 10-45*3.8) + 4*(90347558 BARKABODA 45.1-63.5*3.8) + 3*(10347562 Preparation Wood) + 0.64*(80350184 Same Color Edge Wood)          | 1*(00351984 HÄLLVIKEN inset sink 1 bowl white quartz composite 56x50 cm)                                  | NA                                   | NA                               | 2*(10347562 Cut Out Wood)       | NA                                 | NA                             | NA                               | NA                                   | NA                                   | 4.52*(60216752 ISHULT 1 m2)    | NA                               | NA                               | NA                               | NA                                   | NA                                | NA                                   |
